sonar.projectKey=joe-mccarthy_termfolio
sonar.organization=joe-mccarthy
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/.hugo_build.lock,**/public/**,.public/**,**/*.png,**/*.ico,**/*.woff,**/*.woff2
